---
displayName: NodeJS with PostgreSQL CRUD Stack
description: Stack for developing NodeJS CRUD Web Applications
tags: ["NodeJS", "PostgreSQL", "Alpine"]
projectType: "nodejs-postgres"
language: "nodejs"
version: 0.0.1